=== davidtoro96/practicascurso/xml/dtd externos/productos/productos.dtd
<!ELEMENT Productos (Items*, Impuesto?, Entrega,
Total-productos)>
<!ELEMENT Items ((Cantidad|Volumen), Descripcion,
Precio, Total-item)>
<!ELEMENT Cantidad (#PCDATA)>
<!ELEMENT Volumen (#PCDATA)>
<!ELEMENT Descripcion (#PCDATA)>
<!ELEMENT Precio (#PCDATA)>
<!ELEMENT Total-item (#PCDATA)>
<!ELEMENT Impuesto (#PCDATA)>
<!ELEMENT Entrega (#PCDATA)>
<!ELEMENT Total-productos (#PCDATA)>

=== davidtoro96/practicascurso/xml/dtd externos/productos/productos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Productos SYSTEM "productos.dtd">
<Productos>
  <Items>
    <Cantidad>2</Cantidad>
    <Descripcion>Hamburguesas</Descripcion>
    <Precio>€2.25</Precio>
    <Total-item>€$4.5</Total-item>
  </Items>
  <Items>
    <Volumen>2 Litros</Volumen>
    <Descripcion>Coca Cola</Descripcion>
    <Precio>€1.25</Precio>
    <Total-item>€1.5</Total-item>
  </Items>
  <Impuesto>€0.25</Impuesto>
  <Entrega>A domicilio</Entrega>
  <Total-productos>€6.25</Total-productos>
</Productos>
