=== davidtoro96/practicascurso/xml/Complejos/Indicador3/Indicador3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="alumnos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="alumno" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="alumno">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="dni" type="xs:string"/>
        <xs:element ref="direccion"/>
        <xs:element ref="telefono"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="direccion">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="calle" type="xs:string"/>
        <xs:element name="numero" type="xs:string"/>
        <xs:element name="ciudad" type="xs:string"/>
        <xs:element name="provincia" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="telefono">
    <xs:complexType>
      <xs:sequence minOccurs="0">
        <xs:element name="telefono_fijo" type="xs:string"/>
        <xs:element name="telefono_movil" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== davidtoro96/practicascurso/xml/Complejos/Indicador3/indicado3.xml
<?xml version="1.0" encoding="UTF-8"?>
<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Indicador3.xsd">
 <alumno>
    <nombre>Antonio Pérez</nombre>
    <dni>111</dni>
    <direccion>
         <calle>Calle Fuente</calle>
         <numero>4</numero>
         <ciudad>Jabugo</ciudad>
         <provincia>Huelva</provincia>
    </direccion>
    <telefono>
      <telefono_fijo>959222324</telefono_fijo>
    </telefono>    
</alumno>


 </alumno>
<alumno>
    <nombre>Ramon</nombre>
    <dni>333</dni>
    <direccion>
         <calle>Calle falsa</calle>
         <numero>6</numero>
         <ciudad>corodba</ciudad>
         <provincia>cordoba</provincia>
    </direccion>
    <telefono>
        <telefono_movil>789654109</telefono_movil>
    </telefono>
</alumno>
 
<alumno>
    <nombre>Juan Cabrera</nombre>
    <dni>222</dni>
    <direccion>
        <calle>Calle Jazmin</calle>
        <numero>9</numero>
        <ciudad>toledo</ciudad>
        <provincia>tomate</provincia>
    </direccion>
    <telefono>
        <telefono_fijo>957432098</telefono_fijo>
    </telefono>
</alumno>
</alumnos>
